apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: actividad3
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: actividad3
    tier: mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actividad3-mongodb
  labels:
    app: actividad3
spec:
  selector:
    matchLabels:
      app: actividad3
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: actividad3
        tier: mongodb
    spec:
      containers:
        - image: mongo:latest
          name: mongodb
          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              value: root
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              value: password

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongoconf
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongoconf
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongodb
