apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: actividad3
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: actividad3
    tier: mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actividad3-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actividad3
      tier: mongodb
  template:
    metadata:
      labels:
        app: actividad3
        tier: mongodb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: ebs-attached
                operator: In
                values:
                - "true"
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongoconf
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongoconf
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-ebs-pvc
