apiVersion: v1
kind: Service
metadata:
  name: nodejs
  labels:
    app: actividad3
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: actividad3
    tier: nodejs
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: actividad3-nodejs
  labels:
    app: actividad3
spec:
  selector:
    matchLabels:
      app: actividad3
      tier: nodejs
  template:
    metadata:
      labels:
        app: actividad3
        tier: nodejs
    spec:
      containers:
        - name: nodejs
          image: ginesros658/actividad3:nodeapp
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: CONNECTIONSTRING
              valueFrom:
                secretKeyRef:
                  name: mongoconf
                  key: CONNECTIONSTRING      
          imagePullPolicy: Always